disneystreaming/ssm-helpers

cmd/ssm-run/main.go
Fixes #1 
Dry run output is now verbose level 1 by default, and includes a list of the instances that would be targeted by a given command.
=> Make --dry-run output more verbose by default

cmd/ssm-session/main.go
Will show limit/total count in prompt output.
if --limit > instanceList than smaller number will be shown.
--filter will only show total instances matching filter.
fixes #4
=> Add total instance count to interactive ssm-session prompt

.goreleaser.yml
Need to merge disneystreaming/homebrew-tap#1 first
The next release of ssm-helpers will auto-generate the tap formula and overwrite the changes there.
=> Update formula dependency

cmd/ssm-run/main.go, cmd/ssm-session/main.go
I seriously try to do `-l` almost every time I run ssm-session. I think it might be worth making it shorthand.
Only problem is if we want to make a short flag for `--log-limit`
WDYT?
=> Add -l shorthand for limit

cmd/ssm-run/main.go, cmd/ssm-session/main.go
I'm open to suggestions on defaults for version and commit.
goreleaser will automatically add flags
```
-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
```
We can customize it if we want.
fixes #7
=> Add -version flag

aws/config/config.go, aws/session/session.go, aws/session/types.go, cmd/cmdutil/helpers.go, cmd/flags.go, cmd/root.go, cmd/run.go, cmd/session.go, go.mod, go.sum, ssm/helpers.go, ssm/invocation/runner.go, util/common.go, util/httpx/httpx.go
The original design of ssm-run involved starting an invocation per instance targeted, allowing for what I'd call a "shotgun" approach. Unfortunately, at scale, you start to run into API rate limit issues due to the sheer volume of calls. For any given instance, we had to make an API call each time we:
* got our target list (1 per 50 instances)
* started an invocation (1 per instance)
* checked the status of an invocation (1 base + 1 per 2 seconds, per instance)
This might not sound like a ton, but the relevant SSM APIs have relatively low rate limits, resulting in our invocations behaving inconsistently at best. After talking with the AWS SSM team, we were able to validate the expected behavior for things like instances running OSes incompatible with a given document and concurrency …
=> Use SSM targets instead of doing our own lookups

cmd/flags_test.go, testing/test_commands.sh
Test time! These are to test the flag validation wrappers (e.g., `getProfileList`, `getRegionList`) we're using.
=> Add tests for flag wrapper validation

cmd/flags.go, cmd/flags_test.go, cmd/run.go
Just want to get these merged in before I do a PR for the bigger stuff to trim things down a bit. :)
=> Small flag rename, add ssm-session flag validation

util/common.go
This one is up in the air. It'll give us a more consistent UX between `run` and `session`, but would take away the ability to target things like Resource Groups with `run`. Open to feedback.
=> Prefix SliceToTargets keys with "tag:"

ssm/invocation/runner_test.go, testing/ssm_mocks.go
Cleaning up some unused code and improving test coverage for fetching invocation results.
=> Remove unused function and add runner tests/mocks

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/library-scripts/common-debian.sh, .github/workflows/code_quality.yml, cmd/run.go, ec2/helpers.go, ec2/helpers_test.go, go.sum, ssm/instance/fetch.go, ssm/instance/fetch_test.go, ssm/invocation/runner_test.go, testing/ec2_mocks.go, testing/ssm_mocks.go
This PR includes test fixes, additional developer tooling and a new workflow.
This PR implements a new method on the ssm and ec2 mocks respectively to cover paginator calls. After the included changes tests are passing again.
These changes are:
- Implementing `DescribeInstanceInformationPages` method in the ssm API mocks
- Implementing `DescribeInstancesPages` method in the ec2 API mocks
This PR also introduces a new `code_quality` workflow that handles running `make format` and `make test` on PR creation.
In addition to the above fixes, this PR includes a few additional small changes
- ran a `make format` to format branch
- small cleanups to the pagination callbacks
- addition of a devcontainer for VS Code users
- please let me know if this is a problem and I will happily remove it or …
=> Testing workflow and paginated test fixes

cmd/run.go, ssm/helpers.go, ssm/invocation/runner.go, ssm/invocation/types.go
Ensure errors tracked to later exit properly with error code (1)
(wip)
=> Tracking errors and properly exiting with error code

cmd/flags.go, cmd/flags_test.go
SSM targets only allow a maximum of 5 filters to be passed for a given target. Adding additional targets will lead to a 400 error being returned by SSM.
```
bin/ssm run -f 'tag:a=1,tag:b=2,tag:c=3,tag:d=4,tag:e=5,tag:f=6' -c 'echo foo'
INFO    Command(s) to be executed:
echo foo
ERROR   Error when calling the SendCommand API for account [redacted in [redacted]
ValidationException: 1 validation error detected: Value '[Target(key=tag:a, values=[1]), Target(key=tag:b, values=[2]), Target(key=tag:c, values=[3]), Target(key=tag:d, values=[4]), Target(key=tag:e, values=[5]), Target(key=tag:f, values=[6])]' at 'targets' failed to satisfy constraint: Member must have length less than or equal to 5.
status code: 400, request id: [redacted]
INFO    Instance ID              Region          Profile …
```
=> Validate number of SSM target filters specified

.devcontainer/devcontainer.json, .github/workflows/release.yml, .goreleaser.yml
This PR adds the Github Container Registry as an additional target for docker images. This is to:
- Future proof as Github packages will eventually be superseded by the ghcr.
- Support docker image manifest v2
Additional information is covered on the [Migrating to ghcr](https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry) link. 
In addition to the above fixes, this PR includes a small change to remove an explicit shell setting in the devcontainer spec allowing users to pick their preferred shell for the terminal.
=> Add GHCR as a goreleaser target alongside github packages

.devcontainer/devcontainer.json, .github/workflows/release.yml, .goreleaser.yml, cmd/flags.go, cmd/flags_test.go
=> Pulling changes upstream into main

.goreleaser.yml
Currently our releases pack the binary `ssm` into each tar archive. 
https://github.com/disneystreaming/homebrew-tap/blob/master/Formula/ssm-helpers.rb#L28-L30
This PR fixes a bug where our homebrew releases currently are attempting to install a `ssm-helpers` binary from our released archive rather than `ssm`. As can be seen in https://github.com/disneystreaming/homebrew-tap/blob/master/Formula/ssm-helpers.rb#L28-L30
This change _WILL_ change the binary, but this is a change that brings it into consistency with all other deployments.
We can either,
- Make the breaking change
- Make the breaking change and symlink `ssm-helpers` to the binary
- Update the tar binary to `ssm-helpers` consistently
I'm happy to modify this PR to any of the above options.
=> Add install directive to specify correct homebrew installed binary.

aws/resolver/resolve.go, aws/resolver/resolver_test.go, cmd/cmdutil/helpers.go, cmd/flags.go, cmd/flags_test.go, cmd/run.go, cmd/session.go, cmd/ssm-run/README.md, cmd/ssm-session/README.md, ec2/helpers.go, ec2/helpers_test.go, ssm/helpers.go, ssm/helpers_test.go, ssm/instance/fetch.go, ssm/instance/types.go
This PR adds the capability to lookup an instance ID via the private address of an attached NIC.
Functionally this would be similar to the following bash one-liner
```bash
ssm session -i $(aws ec2 describe-network-interfaces --filters Name=addresses.private-ip-address,Values=<SOME PRIVATE IP> --query 'NetworkInterfaces[0].Attachment.InstanceId' | tr -d '"')
```
However this allows the added convenience of checking across multiple accounts, regions and handling the IP resolution.
```bash
ssm session -a 10.0.10.0
```
```bash
ssm session -a 10.0.10.0,10.0.10.1
```
```bash
ssm session -a some.internal.dns.record.example.com
```
```
bash
ssm session -a 10.0.10.0 -c 'uname -a'
```
- Adds a new flag `--address`/`-a`
- Adds a new Resolver interface
- Adds an `--attribute` flag for additional …
=> Instance lookup by IP and hostname via private IP addresses on attached NIC

.goreleaser.yml
Per https://goreleaser.com/deprecations/#dockerbinaries, release `v0.175.0` removed the `docker.binaries` field. This PR implements the migration from `docker.binaries` -> `docker.ids`.
```
• loading config file       file=.goreleaser.yml
• checking config: 
• snapshotting     
• github/gitlab/gitea releases
• project name     
• loading go mod information
• building binaries
• creating source archive
• archives         
• linux packages   
• snapcraft packages
• calculating checksums
• signing artifacts
• signing docker images
• docker images    
• docker manifests 
• artifactory      
• blobs            
• homebrew tap formula
• scoop manifests  
• discord          
• reddit           
• slack            
• teams            
• twitter          
• milestones       
• config is valid
```
=> Implement `docker.binaries` deprecation mitigation

.github/workflows/code_quality.yml
This PR adds a check step for validating our `.goreleaser.yml`. This was added due to breaking changes being introduced to goreleaser, causing issues in our last two release cuts. A better fix would be to probably pin the version, but this check should atleast both, catch any issues with changes to the file and catch any breaking changes introduced by the tool upstream.
=> Add config check step to goreleaser

.goreleaser.yml
This adds `tmux` as an additional dependency in our homebrew formula as this is currently treated as a runtime dependency.
relates to #61
=> Add tmux as a homebrew dependency
